export const createUserSurvey = () => {
    return {
      user_id: 0,
      gender: null,
      age_group: null,
      cities_5: null,
      cities_4: null,
      cities_3: null,
      cities_2: null,
      cities_1: null,
      izbrannoe: null,
      cities_prosmotr_more: null,
      cities_prosmotr_less: null,
      poznavatelnyj_kulturno_razvlekatelnyj: false,
      delovoy: false,
      etnicheskiy: false,
      religioznyj: false,
      sportivnyj: false,
      obrazovatelnyj: false,
      ekzotic: false,
      ekologicheskiy: false,
      selskij: false,
      lechebno_ozdorovitelnyj: false,
      sobytijnyj: false,
      gornolyzhnyj: false,
      morskie_kruizy: false,
      plyazhnyj_otdykh: false,
      s_detmi: false,
      s_kompaniej_15_24: false,
      s_kompaniej_25_44: false,
      s_kompaniej_45_66: false,
      s_semej: false,
      v_odinochku: false,
      paroj: false,
      kuhnya: false
    };
  }